In [14]:
import pandas as pd
import sqlite3

In [4]:
plans_df = pd.read_csv("../data/plans.csv")
claims_df = pd.read_csv("../data/claims.csv")

In [5]:
plans_df.head()

,plan_id,plan_name,monthly_premium,annual_deductible,copay_pct,coverage_type,network_tier
0,P101,Gold PPO,500,2000,10,PPO,Gold
1,P102,Silver HMO,300,1500,20,HMO,Silver
2,P103,Bronze HMO,150,1000,30,HMO,Bronze

In [6]:
claims_df.head()

  claim_id member_id plan_id procedure  claim_amount    status  date_filed
0    C1001     M1001    P101     X-ray           250   Pending  2023-04-01
1    C1002     M1001    P101   Surgery          1200  Approved  2023-03-15
2    C1003     M1002    P102     X-ray           150    Denied  2023-04-05
3    C1004     M1002    P102   Surgery           900  Approved  2023-03-20
4    C1005     M1003    P103     X-ray            50   Pending  2023-04-10

In [7]:
plans_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   plan_id            3 non-null      object
 1   plan_name          3 non-null      object
 2   monthly_premium    3 non-null      int64
 3   annual_deductible  3 non-null      int64
 4   copay_pct          3 non-null      int64
 5   coverage_type      3 non-null      object
 6   network_tier       3 non-null      object
dtypes: int64(3), object(4)
memory usage: 296.0+ bytes

In [8]:
claims_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   claim_id      5 non-null      object
 1   member_id     5 non-null      object
 2   plan_id       5 non-null      object
 3   procedure     5 non-null      object
 4   claim_amount  5 non-null      int64
 5   status        5 non-null      object
 6   date_filed    5 non-null      object
dtypes: int64(1), object(6)
memory usage: 408.0+ bytes

In [9]:
# Clean the data
# Drop duplicates
plans_df = plans_df.drop_duplicates()
claims_df = claims_df.drop_duplicates()

In [10]:
# Clean the data
#Drop null values
plans_df = plans_df.dropna()
claims_df = claims_df.dropna()

In [11]:
# Coerce date filed to datetime
claims_df['date_filed'] = pd.to_datetime(claims_df['date_filed'])

In [13]:
claims_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   claim_id      5 non-null      object
 1   member_id     5 non-null      object
 2   plan_id       5 non-null      object
 3   procedure     5 non-null      object
 4   claim_amount  5 non-null      int64
 5   status        5 non-null      object
 6   date_filed    5 non-null      datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(5)
memory usage: 408.0+ bytes

In [19]:
conn = sqlite3.connect("../coverage.db")

In [20]:
# Connect plans and claims data to SQLite database
plans_df.to_sql("plans", conn, if_exists="replace", index=False)
claims_df.to_sql("claims", conn, if_exists="replace", index=False)

5